### ISSUE TITLE
[GSK-890] "Target column is not available" message should include "in the dataset"

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#912] opened 2023-04-04 08:40 UTC
Maybe also an example of how to specify a target for a dataset

<sub>From [SyncLinear.com](https://synclinear.com) | [GSK-890](https://linear.app/giskard/issue/GSK-890/target-column-is-not-available-message-should-include-in-the-dataset)</sub>

**Comment by rabah-khalek** [comment] 2023-04-12 14:23
duplicate of an issue that was solved here: [https://github.com/Giskard-AI/giskard/commit/30c2bacd47bb8dcaacf538668a388aacd07d7f7a](https://github.com/Giskard-AI/giskard/commit/30c2bacd47bb8dcaacf538668a388aacd07d7f7a)

**Closed by rabah-khalek** 2023-04-12 14:23 UTC
Labels: user-test, webedia
