### ISSUE TITLE
Feedback modal doesn't open for the second time after it's closed

### ISSUE THREAD

**Issue by andreybavt** [Giskard-AI/giskard#675] opened 2023-01-23 11:41 UTC
After the feedback modal is closed, the url isn't reset to `/feedbacks` and is still `/feedbacks/{id}`

**Comment by andreybavt** [comment] 2023-01-23 12:43
@Googleton could you have a look at this small issue whenever you have time?

**Comment by Googleton** [comment] 2023-01-24 09:52
Do you have more details for a reproduction? I can't get it to happen locally, I'm on main.

**Comment by kevinmessiaen** [comment] 2023-01-25 13:02
Duplicate of #544

**Comment by andreybavt** [comment] 2023-01-25 22:38
Good catch @kevinmessiaen, the first one was originally created 9 months ago 🙈

**Closed** 2023-02-01 21:44 UTC
